[serverCounter]
baseUrl="http://localhost:9080"
cooldown=1

[botlists]
  [botlists.dbotsorg]
  baseUrl="https://discordbots.org/api"
  apiKey=""
  id="508391840525975553"
  [botlists.dblcom]
  baseUrl="https://discordbotlist.com/api"
  token=""
  id="508391840525975553"
